CREATE OR REPLACE FUNCTION BHZ_FC_CALCULA_PRECO_DINAMICO (P_CODPARC FLOAT, P_CODPROD FLOAT, P_CODEMP FLOAT, P_TIPO INT)
RETURN FLOAT
IS
	V_PRECO1 FLOAT;
	V_PRECO2 FLOAT;
	V_PRECO3 FLOAT;

BEGIN

	SELECT
		ROUND(PRECO_MARGEM/(1-(ALIQICMS/100)),2) PRECO1,
		ROUND(PRECO_MARGEM/(1-(ALIQICMS/100)) - ROUND(PRECO_MARGEM/(1-(ALIQICMS/100)),2)*(DESC1/100),2) PRECO2,
		ROUND(PRECO_MARGEM/(1-(ALIQICMS/100)) - ROUND(PRECO_MARGEM/(1-(ALIQICMS/100)),2)*(DESC2/100),2) PRECO3
	INTO
		V_PRECO1,
		V_PRECO2,
		V_PRECO3
	FROM (SELECT
		PRO.CODPROD,
		PRO.DESCRPROD,
		BHZ_OBTEMCUSTO(PRO.CODPROD,'S',1,'N',0,'N',' ',SYSDATE,7) CUSMED_GER,
		MAR.MARGEM,
		ROUND(BHZ_OBTEMCUSTO(PRO.CODPROD,'S',1,'N',0,'N',' ',SYSDATE,7)/(1 - (MAR.MARGEM / 100)),2) PRECO_MARGEM,
		OPTION_LABEL('TGFPRO','ORIGPROD',PRO.ORIGPROD) ORIGEMPROD,
		UFS.UF UFORIG,
		UFSDEST.UF UFDEST,
		NVL(CASE WHEN PRO.TIPSUBST IN ('A','C','P') AND ICM.UFDEST = ICM.UFORIG THEN 0
			 WHEN PAR.CLASSIFICMS = 'C' AND ICM.UFDEST != ICM.UFORIG THEN ICMDIFAL.ALIQUOTA
	         WHEN PRO.ORIGPROD IN (1,2,6,7) AND ICM.UFORIG != ICM.UFDEST  THEN ICM.ALIQESTRANGEIRA ELSE ICM.ALIQUOTA END, 0)
	    + CASE WHEN PRO.GRUPOCOFINS != 'MONOFASICO' THEN 0 ELSE 3.65 END ALIQICMS,
		MAR.DESC1,
		MAR.DESC2
	FROM TGFPRO PRO
	LEFT JOIN AD_TGFMAREMP MAR ON MAR.CODPROD = PRO.CODPROD
	LEFT JOIN TSIEMP EMP ON EMP.CODEMP = MAR.CODEMP
	LEFT JOIN TSICID CID ON CID.CODCID = EMP.CODCID
	LEFT JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
	LEFT JOIN TGFPAR PAR ON PAR.CODPARC = P_CODPARC
	LEFT JOIN TSICID CIDDEST ON CIDDEST.CODCID = PAR.CODCID
	LEFT JOIN TSIUFS UFSDEST ON UFSDEST.CODUF = CIDDEST.UF
	LEFT JOIN TGFICM ICM ON ICM.UFORIG = CID.UF AND ICM.UFDEST = CIDDEST.UF AND ICM.TIPRESTRICAO = 'S' AND ICM.TIPRESTRICAO2 = 'S'
	LEFT JOIN TGFICM ICMDIFAL ON ICMDIFAL.UFORIG = CID.UF AND ICMDIFAL.UFDEST = CID.UF AND ICMDIFAL.TIPRESTRICAO = 'S' AND ICMDIFAL.TIPRESTRICAO2 = 'S'
	LEFT JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
	LEFT JOIN TGFMAR ON TGFMAR.CODIGO = PRO.CODMARCA
	WHERE PRO.CODPROD = P_CODPROD
	  AND MAR.CODEMP = P_CODEMP)  T1;

  IF P_TIPO = 1 THEN
    RETURN(V_PRECO1);
  ELSIF P_TIPO = 2 THEN
    RETURN(V_PRECO2);
  ELSIF P_TIPO = 3 THEN
    RETURN(V_PRECO3);
  ELSE
    RETURN (0);
  END IF;

END;