WITH LIM AS (
  SELECT CODPARC, NVL(LIMCRED,0) AS LIMITE
  FROM TGFPAR
  WHERE CODPARC = :CODPARC
),
ABERTO AS (
  SELECT CODPARC, SUM(VLRDESDOB) AS ABERTO
  FROM TGFFIN
  WHERE CODPARC = :CODPARC
    AND DHBAIXA IS NULL
    AND RECDESP = 1
  GROUP BY CODPARC
)
SELECT
  L.CODPARC,
  L.LIMITE,
  NVL(A.ABERTO,0) AS ABERTO,
  (L.LIMITE - (NVL(A.ABERTO,0)+:VLRNOTA)) AS LIMITEDISP
FROM LIM L
LEFT JOIN ABERTO A ON A.CODPARC = L.CODPARC
