WITH T1 AS (SELECT EMP.CODEMP
FROM TSIEMP EMP
LEFT JOIN TSIUSU USU ON USU.CODUSU = STP_GET_CODUSULOGADO
WHERE (USU.CODEMP = EMP.CODEMP OR USU.CODGRUPO = 2))
SELECT
    T1.CODEMP AS EMPRESA,
    'PREÇO 1' AS DESCRICAO,
    BHZ_FC_CALCULA_PRECO_DINAMICO (NVL(CAB.CODPARC,NVL(:CODPARC,T1.CODEMP)),:CODPROD,T1.CODEMP,1) AS PRECO
FROM T1
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = NVL(:NUNOTA,0)
UNION ALL
SELECT
    T1.CODEMP AS EMPRESA,
    'PREÇO 2' AS DESCRICAO,
    BHZ_FC_CALCULA_PRECO_DINAMICO (NVL(CAB.CODPARC,NVL(:CODPARC,T1.CODEMP)),:CODPROD,T1.CODEMP,2) AS PRECO
FROM T1
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = NVL(:NUNOTA,0)
UNION ALL
SELECT
    T1.CODEMP AS EMPRESA,
    'PREÇO 3' AS DESCRICAO,
    BHZ_FC_CALCULA_PRECO_DINAMICO (NVL(CAB.CODPARC,NVL(:CODPARC,T1.CODEMP)),:CODPROD,T1.CODEMP,3) AS PRECO
FROM T1
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = NVL(:NUNOTA,0)